module.exports = {
    BRAND_NOT_FOUND:
        "BRAND_NOT_FOUND",

    BRAND_DUPLICATE_SLUG:
        "BRAND_DUPLICATE_SLUG",

    BRAND_DELETED:
        "BRAND_DELETED",

    INTERNAL_SERVER_ERROR:
        "INTERNAL_SERVER_ERROR",
        
    BRAND_NOT_FOUND_OR_DELETED:
        "BRAND_NOT_FOUND_OR_DELETED",

    ATTRIBUTE_NOT_FOUND:
        "ATTRIBUTE_NOT_FOUND",

    ATTRIBUTE_DUPLICATE_SLUG:
        "ATTRIBUTE_DUPLICATE_SLUG",

    ATTRIBUTE_DUPLICATE_CODE:
        "ATTRIBUTE_DUPLICATE_CODE",

    ATTRIBUTE_NOT_FOUND_OR_DELETED:
        "ATTRIBUTE_NOT_FOUND_OR_DELETED",

    ROLE_NOT_FOUND:
        "ROLE_NOT_FOUND",

    ROLE_DUPLICATE:
        "ROLE_DUPLICATE",

    ROLE_DELETED:
        "ROLE_DELETED",

    ROLE_NOT_FOUND_OR_DELETED:
        "ROLE_NOT_FOUND_OR_DELETED"
};