module.exports = {
    BRAND_NOT_FOUND:
        "BRAND_NOT_FOUND",

    BRAND_DUPLICATE_SLUG:
        "BRAND_DUPLICATE_SLUG",

    BRAND_DELETED:
        "BRAND_DELETED",

    INTERNAL_SERVER_ERROR:
        "INTERNAL_SERVER_ERROR",
        
    BRAND_NOT_FOUND_OR_DELETED:
        "BRAND_NOT_FOUND_OR_DELETED",

    ATTRIBUTE_NOT_FOUND:
        "ATTRIBUTE_NOT_FOUND",

    ATTRIBUTE_DUPLICATE_SLUG:
        "ATTRIBUTE_DUPLICATE_SLUG",

    ATTRIBUTE_DUPLICATE_CODE:
        "ATTRIBUTE_DUPLICATE_CODE",

    ATTRIBUTE_NOT_FOUND_OR_DELETED:
        "ATTRIBUTE_NOT_FOUND_OR_DELETED",

    ROLE_NOT_FOUND:
        "ROLE_NOT_FOUND",

    ROLE_DUPLICATE:
        "ROLE_DUPLICATE",

    ROLE_DELETED:
        "ROLE_DELETED",

    ROLE_NOT_FOUND_OR_DELETED:
        "ROLE_NOT_FOUND_OR_DELETED",

    ACCOUNT_NOT_FOUND:
        "ACCOUNT_NOT_FOUND",

    ACCOUNT_DUPLICATE_EMAIL:
        "ACCOUNT_DUPLICATE_EMAIL",

    ACCOUNT_DELETED:
        "ACCOUNT_DELETED",

    ACCOUNT_INVALID_ID:
        "ACCOUNT_INVALID_ID",

    USER_NOT_FOUND:
        "USER_NOT_FOUND",

    USER_NOT_FOUND_OR_DELETED:
        "USER_NOT_FOUND_OR_DELETED",

    USER_NOT_FOUND_OR_NOT_DELETED:
        "USER_NOT_FOUND_OR_NOT_DELETED",

    CATEGORY_NOT_FOUND:
        "CATEGORY_NOT_FOUND",

    CATEGORY_DUPLICATE_SLUG:
        "CATEGORY_DUPLICATE_SLUG",

    CATEGORY_HAS_CHILDREN:
        "CATEGORY_HAS_CHILDREN",

    CATEGORY_REQUIRED_IMAGE:
        "CATEGORY_REQUIRED_IMAGE",

    CATEGORY_MISSING_ID:
        "CATEGORY_MISSING_ID",

    CATEGORY_MISSING_TITLE:
        "CATEGORY_MISSING_TITLE",

    CATEGORY_INVALID_PARENT:
        "CATEGORY_INVALID_PARENT",

    CATEGORY_CIRCULAR_DEPENDENCY:
        "CATEGORY_CIRCULAR_DEPENDENCY",

    CATEGORY_EXCEED_LEVEL_LIMIT:
        "CATEGORY_EXCEED_LEVEL_LIMIT"
};