name: lesson2-steps

on:
  workflow_dispatch:
jobs:
  lesson2-steps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chekout source
        uses: actions/checkout@v6
      
      - name: show directory
        run : ls -la
      
      - name : show version node 
        run: node -v
        